import { Router } from "express";
import { authRoutes } from "./auth.routes.js";
import { usersRoutes } from "./users.routes.js";
import { storesRoutes } from "./stores.routes.js";
import { captainsRoutes } from "./captains.routes.js";
import { ordersRoutes } from "./orders.routes.js";
import { trackingRoutes } from "./tracking.routes.js";
import { notificationsRoutes } from "./notifications.routes.js";
import { activityRoutes } from "./activity.routes.js";
import { dashboardSettingsRoutes } from "./dashboard-settings.routes.js";
import { geocodeRoutes } from "./geocode.routes.js";
import { mobileRoutes } from "./mobile/index.js";
import { customerRoutes } from "./customer.routes.js";
import { superAdminWalletsRoutes } from "./super-admin-wallets.routes.js";
import { supervisorCaptainTransferRoutes } from "./supervisor-captain-transfer.routes.js";
import { walletReadRoutes } from "./wallet-read.routes.js";
import { reportsRoutes } from "./reports.routes.js";
import { branchesRoutes } from "./branches.routes.js";
import { zonesRoutes } from "./zones.routes.js";
import { companiesRoutes } from "./companies.routes.js";
import { publicRoutes } from "./public.routes.js";
import { complaintsRoutes } from "./complaints.routes.js";
import { companyPublicPageRoutes } from "./company-public-page.routes.js";
import { adminCaptainApplicationsRoutes } from "./admin-captain-applications.routes.js";

const v1Router = Router();

v1Router.use("/admin/captain-applications", adminCaptainApplicationsRoutes);
v1Router.use("/public", publicRoutes);
v1Router.use("/", companyPublicPageRoutes);
v1Router.use("/complaints", complaintsRoutes);
v1Router.use("/auth", authRoutes);
v1Router.use("/users", usersRoutes);
v1Router.use("/stores", storesRoutes);
v1Router.use("/captains", captainsRoutes);
v1Router.use("/orders", ordersRoutes);
v1Router.use("/tracking", trackingRoutes);
v1Router.use("/notifications", notificationsRoutes);
v1Router.use("/activity", activityRoutes);
v1Router.use("/dashboard-settings", dashboardSettingsRoutes);
v1Router.use("/geocode", geocodeRoutes);
v1Router.use("/mobile", mobileRoutes);
v1Router.use("/customer", customerRoutes);
v1Router.use("/super-admin/wallets", superAdminWalletsRoutes);
v1Router.use("/supervisor/wallets", supervisorCaptainTransferRoutes);
v1Router.use("/finance", walletReadRoutes);
v1Router.use("/reports", reportsRoutes);
v1Router.use("/branches", branchesRoutes);
v1Router.use("/zones", zonesRoutes);
v1Router.use("/companies", companiesRoutes);

export { v1Router };
